# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('url', models.TextField(max_length=500)),
                ('text', models.TextField(max_length=500)),
                ('score', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('origin', models.CharField(max_length=30)),
                ('is_video', models.BooleanField(default=False)),
            ],
        ),
    ]
