# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
