# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.TextField(default='', max_length=200),
        ),
    ]
