# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0006_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
